export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const FINISH_TODO = 'FINISH_TODO'
export const HIDDEN_TODO = 'HIDDEN_TODO'
